version: 2

jobs:
    build:
        docker:
            -
                image: hashicorp/terraform:0.11.11

        steps:
            - checkout

            -
                run:
                    name: Init
                    command: terraform init

            -
                run:
                    name: Validate
                    command: terraform validate
